import { cp, mkdir, rm, readFile, writeFile } from 'node:fs/promises';

await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });

const indexPath = 'dist/index.html';
let html = await readFile(indexPath, 'utf8');
html = html.replace('</head>', '  <link rel="stylesheet" href="/purchase-check.css" />\n  <link rel="stylesheet" href="/monthly-margin.css" />\n  <link rel="stylesheet" href="/smart-insights.css" />\n  <link rel="stylesheet" href="/subscriptions.css" />\n  <link rel="stylesheet" href="/money-search.css" />\n  <link rel="stylesheet" href="/transaction-editor.css" />\n  <link rel="stylesheet" href="/scenario-planner.css" />\n  <link rel="stylesheet" href="/japan-actual.css" />\n  <link rel="stylesheet" href="/trip-budgets.css" />\n  <link rel="stylesheet" href="/japan-wallet.css" />\n  <link rel="stylesheet" href="/data-quality.css" />\n  <link rel="stylesheet" href="/japan-costs.css" />\n  <link rel="stylesheet" href="/budget-system.css" />\n  <link rel="stylesheet" href="/budget-guidance.css" />\n  <link rel="stylesheet" href="/budget-funding.css" />\n  <link rel="stylesheet" href="/budget-health.css" />\n  <link rel="stylesheet" href="/budget-ready.css" />\n  <link rel="stylesheet" href="/budget-template.css" />\n  <link rel="stylesheet" href="/month-handoff.css" />\n  <link rel="stylesheet" href="/true-expense-funding.css" />\n</head>');
html = html.replace('</body>', '  <script type="module" src="/purchase-check.js"></script>\n  <script type="module" src="/monthly-margin.js"></script>\n  <script type="module" src="/smart-insights.js"></script>\n  <script type="module" src="/subscriptions.js"></script>\n  <script type="module" src="/money-search.js"></script>\n  <script type="module" src="/transaction-editor.js"></script>\n  <script type="module" src="/scenario-planner.js"></script>\n  <script type="module" src="/japan-actual.js"></script>\n  <script type="module" src="/trip-budgets.js"></script>\n  <script type="module" src="/japan-wallet.js"></script>\n  <script type="module" src="/data-quality.js"></script>\n  <script type="module" src="/japan-costs.js"></script>\n  <script type="module" src="/budget-system.js"></script>\n  <script type="module" src="/budget-guidance.js"></script>\n  <script type="module" src="/budget-funding.js"></script>\n  <script type="module" src="/budget-health.js"></script>\n  <script type="module" src="/budget-ready.js"></script>\n  <script type="module" src="/budget-template.js"></script>\n  <script type="module" src="/month-handoff.js"></script>\n  <script type="module" src="/true-expense-funding.js"></script>\n</body>');
await writeFile(indexPath, html);

console.log('MoneyOS assets copied and decision tools injected');
