import { neon } from '@neondatabase/serverless';
import { isAuthenticated } from '../lib/auth.js';

const monthPattern=/^\d{4}-(0[1-9]|1[0-2])$/;
const MAX=10_000_000;
function money(v){const n=Number(v??0);return Number.isFinite(n)?Math.max(0,Math.min(MAX,Math.round(n*100)/100)):0;}
function text(v,max=80){return String(v??'').trim().slice(0,max);}
function monthOr(v,fallback){const s=text(v,7);return monthPattern.test(s)?s:fallback;}
function nextMonth(month){const[y,m]=month.split('-').map(Number);const d=new Date(Date.UTC(y,m,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
function median(values){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2;}
function defaultBucket(name){if(['Refusjoner og delte utgifter','Sparing'].includes(name))return'excluded';if(['Digitale tjenester','Mobil og internett','Forsikring','Bolig'].includes(name))return'fixed';if(['Dagligvarer','Transport','Helse','Utdanning','Bank og gebyrer'].includes(name))return'essential';return'flex';}
function validDate(v){const s=text(v,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null;}
function fundContribution(fund,month,committed=0){const target=money(fund?.target_amount_nok),saved=money(fund?.saved_nok)+money(committed),remaining=Math.max(0,target-saved);if(fund?.is_active===false||remaining<=0)return 0;if(fund?.monthly_nok!=null&&Number(fund.monthly_nok)>0)return Math.min(money(fund.monthly_nok),remaining);const td=validDate(fund?.target_date);if(!td)return 0;const[y,m]=month.split('-').map(Number),[ty,tm]=td.slice(0,7).split('-').map(Number);const months=Math.max(1,(ty-y)*12+(tm-m)+1);return Math.ceil(remaining/months*100)/100;}
function spentByFund(summary){const out={};for(const link of Object.values(summary?.true_expense_transaction_map??{})){const id=String(link?.fund_id??'');if(!id)continue;out[id]=money((out[id]??0)+money(link?.expense_amount_nok));}return out;}
async function configRow(sql){const rows=await sql`SELECT id,COALESCE(extracted_summary,'{}'::jsonb) AS summary FROM documents WHERE document_type='moneyos_config' AND source_name='MoneyOS private config' ORDER BY document_date DESC NULLS LAST,created_at DESC LIMIT 1`;return rows[0]??null;}
async function latestSalary(sql){const rows=await sql`SELECT t.id::text AS id,t.transaction_date,ROUND(t.amount::numeric,2) AS amount,t.merchant,t.description FROM transactions t WHERE t.transaction_type='income' AND COALESCE(t.is_pending,false)=false AND lower(COALESCE(t.description,'')) LIKE '%lønn%' ORDER BY t.transaction_date DESC,t.id DESC LIMIT 1`;return rows[0]??null;}
async function salaryById(sql,id){const rows=await sql`SELECT t.id::text AS id,t.transaction_date,ROUND(t.amount::numeric,2) AS amount,t.merchant,t.description FROM transactions t WHERE t.id::text=${id} AND t.transaction_type='income' AND COALESCE(t.is_pending,false)=false AND lower(COALESCE(t.description,'')) LIKE '%lønn%' LIMIT 1`;return rows[0]??null;}
async function recentIncomes(sql){return sql`SELECT t.id::text AS id,t.transaction_date,ROUND(t.amount::numeric,2) AS amount,t.merchant,t.description FROM transactions t WHERE t.transaction_type='income' AND COALESCE(t.is_pending,false)=false AND t.transaction_date>=CURRENT_DATE-interval '120 days' ORDER BY t.transaction_date DESC,t.id DESC LIMIT 20`;}

async function buildMonth(sql,config,month){
  const categoriesRows=await sql`SELECT name FROM categories ORDER BY name`,categories=categoriesRows.map(x=>x.name);
  const[historyRows,recurringRows,dashboardRows,salary,incomeRows]=await Promise.all([
    sql`SELECT extracted_summary->'monthly' AS monthly FROM documents WHERE extracted_summary ? 'monthly' ORDER BY document_date DESC NULLS LAST,created_at DESC LIMIT 1`,
    sql`SELECT r.name,r.amount,r.cadence,r.next_due_date,ROUND((CASE r.cadence WHEN 'daily' THEN r.amount*365.25/12 WHEN 'weekly' THEN r.amount*52/12 WHEN 'biweekly' THEN r.amount*26/12 WHEN 'monthly' THEN r.amount WHEN 'quarterly' THEN r.amount/3 WHEN 'yearly' THEN r.amount/12 ELSE r.amount END)::numeric,2) AS monthly_amount FROM recurring_items r WHERE r.item_type='expense' AND r.is_active=true`,
    sql`SELECT finance_dashboard() AS dashboard`,latestSalary(sql),recentIncomes(sql)
  ]);
  const historical=historyRows[0]?.monthly??{},historyMonths=Object.keys(historical).filter(k=>monthPattern.test(k)&&k<month).sort().reverse().slice(0,6),system=config.summary?.budget_system??{},plan=system.month_plans?.[month]??null;
  let essential=0;const categoryDetail=[];
  for(const name of categories){const saved=plan?.category_targets?.[name],bucket=['fixed','essential','flex','excluded'].includes(saved?.bucket)?saved.bucket:defaultBucket(name),suggestion=Math.round(median(historyMonths.map(k=>Number(historical?.[k]?.expenses?.[name]??0)))*100)/100,target=saved?money(saved.target_nok):(bucket==='essential'?money(suggestion):0);if(bucket==='essential')essential+=target;categoryDetail.push({name,bucket,target_nok:target,suggested_nok:money(suggestion)});}
  const fixed=recurringRows.reduce((s,x)=>s+Number(x.monthly_amount??0),0),fundingRoot=system.funding??{},trueExpenseReserves=fundingRoot.true_expense_reserves??{},spentMap=spentByFund(config.summary),rawFunds=Array.isArray(system.sinking_funds)?system.sinking_funds:[];
  const trueExpenseFunds=rawFunds.filter(f=>f?.is_active!==false).map(f=>{const id=String(f.id),reserved=money(trueExpenseReserves?.[id]?.reserved_nok),spent=money(spentMap[id]),opening=money(f.saved_nok),effective=Math.min(money(f.target_amount_nok),opening+reserved+spent);return{...f,reserved_nok:reserved,spent_nok:spent,effective_saved_nok:effective,remaining_to_goal_nok:Math.max(0,money(f.target_amount_nok)-effective),monthly_contribution_nok:fundContribution(f,month,reserved+spent)};});
  const sinking=trueExpenseFunds.reduce((s,f)=>s+money(f.monthly_contribution_nok),0),savings=money(plan?.savings_target_nok),planningIncome=plan?.planning_income_nok==null?null:money(plan.planning_income_nok),flex=planningIncome==null?0:Math.max(0,planningIncome-fixed-essential-sinking-savings),minimum=fixed+essential,robust=minimum+sinking,full=robust+savings+flex,funding=fundingRoot.allocations??{},funded=money(funding?.[month]?.funded_nok),currentMonth=new Date().toISOString().slice(0,7),activeFunding=Object.entries(funding).filter(([key,value])=>monthPattern.test(key)&&key>currentMonth&&money(value?.funded_nok)>0),allAllocated=activeFunding.reduce((s,[,x])=>s+money(x?.funded_nok),0),trueReservedTotal=Object.values(trueExpenseReserves).reduce((s,x)=>s+money(x?.reserved_nok),0),reservedTotal=allAllocated+trueReservedTotal,dashboard=dashboardRows[0]?.dashboard??{},safe=money(dashboard?.overview?.safe_to_spend),available=Math.max(0,safe-reservedTotal),incomeAllocations=fundingRoot.income_allocations??{};
  const latestSalaryInfo=salary?{id:String(salary.id),transaction_date:salary.transaction_date,amount_nok:money(salary.amount),merchant:salary.merchant??null,description:salary.description??null,already_allocated:!!incomeAllocations[String(salary.id)],allocation:incomeAllocations[String(salary.id)]??null}:null,recentIncome=incomeRows.map(row=>{const assignment=incomeAllocations[String(row.id)]??null;return{id:String(row.id),transaction_date:row.transaction_date,amount_nok:money(row.amount),merchant:row.merchant??null,description:row.description??null,explicit_assignment:assignment?{target_month:assignment.target_month??null,reserved_nok:money(assignment.reserved_nok),left_unassigned_nok:money(assignment.left_unassigned_nok),allocated_at:assignment.allocated_at??null}:null};}),fundingByMonth=activeFunding.sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>({month:key,funded_nok:money(value?.funded_nok),source:value?.source??null,updated_at:value?.updated_at??null})),tiers={minimum:{goal_nok:money(minimum),funded_nok:Math.min(funded,minimum)},true_expenses:{goal_nok:money(sinking),funded_nok:Math.min(Math.max(0,funded-minimum),sinking)},savings:{goal_nok:money(savings),funded_nok:Math.min(Math.max(0,funded-robust),savings)},flex:{goal_nok:money(flex),funded_nok:Math.min(Math.max(0,funded-robust-savings),flex)}};
  return{month,plan_saved:!!plan,planning_income_nok:planningIncome,fixed_nok:money(fixed),essential_nok:money(essential),sinking_nok:money(sinking),savings_nok:savings,flex_nok:money(flex),minimum_month_nok:money(minimum),robust_month_nok:money(robust),full_month_nok:money(full),funded_nok:funded,remaining_to_minimum_nok:money(Math.max(0,minimum-funded)),remaining_to_robust_nok:money(Math.max(0,robust-funded)),remaining_to_full_nok:money(Math.max(0,full-funded)),funded_percent_full:full>0?Math.min(100,Math.round(funded/full*1000)/10):0,tiers,available_to_allocate_nok:available,ready_to_assign_nok:money(available),safe_to_spend_before_funding_nok:safe,base_safe_to_spend_nok:safe,total_future_funding_nok:money(allAllocated),reserved_future_nok:money(allAllocated),reserved_true_expenses_nok:money(trueReservedTotal),reserved_total_nok:money(reservedTotal),overcommitted_nok:money(Math.max(0,reservedTotal-safe)),funding_by_month:fundingByMonth,true_expense_funds:trueExpenseFunds,recent_income:recentIncome,latest_salary:latestSalaryInfo,category_detail,history_months_used:historyMonths};
}
function previewAllocation(model,amount){let left=money(amount);const steps=[],defs=[['minimum','Minimum måned',model.remaining_to_minimum_nok],['true_expenses','True expenses',Math.max(0,model.remaining_to_robust_nok-model.remaining_to_minimum_nok)],['savings','Spare-/reserve-mål',Math.max(0,model.savings_nok-model.tiers.savings.funded_nok)],['flex','Fri pott',Math.max(0,model.flex_nok-model.tiers.flex.funded_nok)]];for(const[key,label,needRaw]of defs){const need=money(needRaw),use=Math.min(left,need);steps.push({key,label,needed_nok:need,allocated_nok:money(use)});left-=use;}return{amount_nok:money(amount),reserved_nok:money(amount-left),left_unassigned_nok:money(left),steps};}

export default async function handler(req,res){
  res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('Pragma','no-cache');
  try{
    if(!isAuthenticated(req))return res.status(401).json({error:'Unauthorized'});if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');
    const sql=neon(process.env.DATABASE_URL),config=await configRow(sql);if(!config)return res.status(500).json({error:'MoneyOS-konfigurasjonen mangler'});const nowMonth=new Date().toISOString().slice(0,7),month=monthOr(req.method==='GET'?req.query?.month:req.body?.month,nextMonth(nowMonth)),model=await buildMonth(sql,config,month);
    if(req.method==='GET'){const amount=Math.min(money(req.query?.amount_nok),model.available_to_allocate_nok);return res.status(200).json({...model,allocation_preview:amount>0?previewAllocation(model,amount):null});}
    if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
    const action=text(req.body?.action,30),current=config.summary?.budget_system??{},funding={...(current.funding??{}),allocations:{...(current.funding?.allocations??{})},income_allocations:{...(current.funding?.income_allocations??{})},true_expense_reserves:{...(current.funding?.true_expense_reserves??{})}},monthAction=['set_funding','allocate_amount','allocate_salary'].includes(action);if(monthAction&&month<=nowMonth)return res.status(409).json({error:'MoneyOS reserverer bare penger til fremtidige måneder. Inneværende måned er allerede aktiv.'});
    if(action==='set_funding'){const requested=money(req.body?.funded_nok),existing=money(funding.allocations?.[month]?.funded_nok),maxAllowed=existing+money(model.available_to_allocate_nok);if(requested>maxAllowed+0.01)return res.status(409).json({error:`Bare ${Math.round(maxAllowed)} kr kan reserveres uten å bruke penger MoneyOS allerede trenger.`});funding.allocations[month]={funded_nok:requested,updated_at:new Date().toISOString(),source:'manual'};}
    else if(action==='allocate_amount'){const amount=money(req.body?.amount_nok);if(amount<=0)return res.status(400).json({error:'Beløpet må være større enn 0'});const preview=previewAllocation(model,Math.min(amount,model.available_to_allocate_nok)),existing=money(funding.allocations?.[month]?.funded_nok);funding.allocations[month]={funded_nok:money(existing+preview.reserved_nok),updated_at:new Date().toISOString(),source:'priority_allocation'};}
    else if(action==='allocate_salary'){const transactionId=text(req.body?.transaction_id,128);if(!transactionId)return res.status(400).json({error:'Mangler lønnstransaksjon'});if(funding.income_allocations[transactionId])return res.status(409).json({error:'Denne lønnen er allerede fordelt i MoneyOS'});const salary=await salaryById(sql,transactionId);if(!salary)return res.status(404).json({error:'Fant ikke en bokført lønnsutbetaling'});const amount=Math.min(money(salary.amount),model.available_to_allocate_nok),preview=previewAllocation(model,amount);if(preview.reserved_nok<=0)return res.status(409).json({error:'Ingen ledige penger kan reserveres til denne måneden nå'});const existing=money(funding.allocations?.[month]?.funded_nok);funding.allocations[month]={funded_nok:money(existing+preview.reserved_nok),updated_at:new Date().toISOString(),source:'salary_priority'};funding.income_allocations[transactionId]={target_month:month,salary_amount_nok:money(salary.amount),reserved_nok:preview.reserved_nok,left_unassigned_nok:money(money(salary.amount)-preview.reserved_nok),allocated_at:new Date().toISOString()};}
    else if(action==='fund_true_expense'){const fundId=text(req.body?.fund_id,80),fund=(current.sinking_funds??[]).find(x=>String(x?.id)===fundId&&x?.is_active!==false),modelFund=model.true_expense_funds?.find(x=>String(x?.id)===fundId);if(!fund||!modelFund)return res.status(404).json({error:'Fant ikke True Expense-målet'});const existing=money(funding.true_expense_reserves?.[fundId]?.reserved_nok),room=money(modelFund.remaining_to_goal_nok),requested=money(req.body?.amount_nok),add=Math.min(requested,room,model.available_to_allocate_nok);if(requested<=0)return res.status(400).json({error:'Beløpet må være større enn 0'});if(add<=0)return res.status(409).json({error:room<=0?'Målet er allerede finansiert eller betalt':'Ingen ufordelte trygge penger er tilgjengelige'});funding.true_expense_reserves[fundId]={reserved_nok:money(existing+add),updated_at:new Date().toISOString(),source:'explicit_true_expense'};}
    else if(action==='release_true_expense'){const fundId=text(req.body?.fund_id,80),existing=money(funding.true_expense_reserves?.[fundId]?.reserved_nok);if(existing<=0)return res.status(409).json({error:'Dette målet har ingen MoneyOS-reserve å frigi'});const requested=money(req.body?.amount_nok),release=requested>0?Math.min(requested,existing):existing,left=money(existing-release);if(left>0)funding.true_expense_reserves[fundId]={...(funding.true_expense_reserves[fundId]??{}),reserved_nok:left,updated_at:new Date().toISOString()};else delete funding.true_expense_reserves[fundId];}
    else if(action==='clear_funding'){delete funding.allocations[month];for(const[id,entry]of Object.entries(funding.income_allocations)){if(entry?.target_month===month)delete funding.income_allocations[id];}}
    else return res.status(400).json({error:'Ukjent handling'});
    const next={...current,version:Math.max(4,Number(current.version??1)),funding,updated_at:new Date().toISOString()};await sql`UPDATE documents SET extracted_summary=jsonb_set(COALESCE(extracted_summary,'{}'::jsonb),'{budget_system}',${JSON.stringify(next)}::jsonb,true) WHERE id=${config.id}`;const updatedConfig={...config,summary:{...config.summary,budget_system:next}},updated=await buildMonth(sql,updatedConfig,month);return res.status(200).json({ok:true,...updated});
  }catch(error){console.error(error);return res.status(500).json({error:'Kunne ikke oppdatere finansieringen'});}
}
