import { neon } from '@neondatabase/serverless';
import { isAuthenticated } from '../lib/auth.js';

const tripBuckets = ['transport', 'stay', 'food', 'activities', 'other'];
function cleanRuleText(value){return String(value??'').trim().replace(/\s+/g,' ').slice(0,120);}
function money(value){const n=Number(value??0);return Number.isFinite(n)?Math.max(0,Math.round(n*100)/100):0;}
async function getPrivateConfig(sql){const rows=await sql`SELECT id,COALESCE(extracted_summary,'{}'::jsonb) AS summary FROM documents WHERE document_type='moneyos_config' AND source_name='MoneyOS private config' ORDER BY document_date DESC NULLS LAST,created_at DESC LIMIT 1`;return rows[0]??null;}

export default async function handler(req,res){
  res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('Pragma','no-cache');
  try{
    if(!isAuthenticated(req))return res.status(401).json({error:'Unauthorized'});
    if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');
    const sql=neon(process.env.DATABASE_URL);
    if(req.method==='GET'){
      const rawLimit=Number(req.query?.limit??80),limit=Number.isFinite(rawLimit)?Math.max(10,Math.min(200,Math.trunc(rawLimit))):80;
      const[transactions,categories,config]=await Promise.all([
        sql`SELECT t.id::text AS id,t.transaction_date,ROUND(t.amount::numeric,2) AS amount,t.merchant,t.description,t.transaction_type,COALESCE(t.is_pending,false) AS is_pending,a.name AS account,COALESCE(c.name,'Annet') AS category FROM transactions t JOIN accounts a ON a.id=t.account_id LEFT JOIN categories c ON c.id=t.category_id ORDER BY t.transaction_date DESC,t.id DESC LIMIT ${limit}`,
        sql`SELECT name FROM categories ORDER BY name`,getPrivateConfig(sql)
      ]);
      const tripMap=config?.summary?.trip_transaction_map??{},trueMap=config?.summary?.true_expense_transaction_map??{},walletMap=config?.summary?.japan?.wallets?.bank_transfer_links??{},trips=Array.isArray(config?.summary?.japan?.trips)?config.summary.japan.trips:[],funds=Array.isArray(config?.summary?.budget_system?.sinking_funds)?config.summary.budget_system.sinking_funds:[];
      const enriched=transactions.map(row=>({...row,trip_id:tripMap?.[row.id]?.trip_id??null,trip_bucket:tripMap?.[row.id]?.bucket??null,true_expense_id:trueMap?.[row.id]?.fund_id??null,true_expense_amount_nok:money(trueMap?.[row.id]?.expense_amount_nok),true_expense_reserve_consumed_nok:money(trueMap?.[row.id]?.reserve_consumed_nok),japan_wallet_transfer:walletMap?.[row.id]?{wallet:walletMap[row.id].wallet,amount_jpy:Number(walletMap[row.id].amount_jpy??0),bank_amount_nok:money(walletMap[row.id].bank_amount_nok),linked_at:walletMap[row.id].linked_at}:null}));
      return res.status(200).json({transactions:enriched,categories:categories.map(row=>row.name),merchant_rules:config?.summary?.merchant_rules??[],trips:trips.map(trip=>({id:trip.id,name:trip.name,start_date:trip.start_date,end_date:trip.end_date})),trip_buckets:tripBuckets,true_expense_funds:funds.filter(f=>f?.is_active!==false).map(f=>({id:f.id,name:f.name,target_amount_nok:money(f.target_amount_nok)}))});
    }
    if(req.method==='PATCH'){
      const id=String(req.body?.id??'').trim(),merchantInput=req.body?.merchant,merchant=merchantInput==null?null:String(merchantInput).trim(),category=String(req.body?.category??'').trim(),transactionType=String(req.body?.transaction_type??'').trim(),rememberRule=req.body?.remember_rule===true,matchText=cleanRuleText(req.body?.match_text),tripId=req.body?.trip_id==null||req.body.trip_id===''?null:String(req.body.trip_id).trim(),tripBucket=tripId?String(req.body?.trip_bucket??'').trim():null,trueExpenseId=req.body?.true_expense_id==null||req.body.true_expense_id===''?null:String(req.body.true_expense_id).trim();
      if(!id||id.length>128)return res.status(400).json({error:'Ugyldig transaksjon'});if(merchant&&merchant.length>160)return res.status(400).json({error:'Merchant-navnet er for langt'});if(!category||category.length>120)return res.status(400).json({error:'Velg en kategori'});if(!['expense','income','transfer'].includes(transactionType))return res.status(400).json({error:'Ugyldig transaksjonstype'});if(rememberRule&&matchText.length<3)return res.status(400).json({error:'Match-teksten må være minst 3 tegn'});if(tripId&&transactionType!=='expense')return res.status(400).json({error:'Bare utgifter kan knyttes til en tur'});if(tripId&&!tripBuckets.includes(tripBucket))return res.status(400).json({error:'Velg hvilken turpost kjøpet tilhører'});if(trueExpenseId&&transactionType!=='expense')return res.status(400).json({error:'Bare utgifter kan bruke en True Expense-reserve'});
      const[current,categoryRows,config]=await Promise.all([sql`SELECT id::text AS id,COALESCE(is_pending,false) AS is_pending,merchant,description,ROUND(amount::numeric,2) AS amount,transaction_type FROM transactions WHERE id::text=${id} LIMIT 1`,sql`SELECT id FROM categories WHERE name=${category} LIMIT 1`,getPrivateConfig(sql)]);
      if(!current.length)return res.status(404).json({error:'Transaksjonen finnes ikke'});if(current[0].is_pending)return res.status(409).json({error:'Vent til transaksjonen er bokført før du endrer den'});if(!categoryRows.length)return res.status(400).json({error:'Kategorien finnes ikke'});if(!config)return res.status(500).json({error:'MoneyOS-konfigurasjonen mangler'});
      const walletLink=config.summary?.japan?.wallets?.bank_transfer_links?.[id]??null;if(walletLink&&transactionType!=='transfer')return res.status(409).json({error:'Denne bankposten finansierer Japan-lommeboken. Fjern bank→Cash/ICOCA-koblingen før den kan bli en vanlig utgift.'});
      const trips=Array.isArray(config.summary?.japan?.trips)?config.summary.japan.trips:[],funds=Array.isArray(config.summary?.budget_system?.sinking_funds)?config.summary.budget_system.sinking_funds:[];if(tripId&&!trips.some(trip=>String(trip?.id)===tripId))return res.status(400).json({error:'Turen finnes ikke'});if(trueExpenseId&&!funds.some(f=>String(f?.id)===trueExpenseId&&f?.is_active!==false))return res.status(400).json({error:'True Expense-målet finnes ikke'});
      const categoryId=categoryRows[0].id;const updated=await sql`UPDATE transactions SET merchant=${merchant||null},category_id=${categoryId},transaction_type=${transactionType} WHERE id::text=${id} RETURNING id::text AS id,transaction_date,amount,merchant,description,transaction_type,is_pending`;
      let matched=1,summary=config.summary??{};
      if(rememberRule){const matchedRows=await sql`UPDATE transactions SET merchant=${merchant||null},category_id=${categoryId},transaction_type=${transactionType} WHERE COALESCE(is_pending,false)=false AND id::text<>${id} AND lower(COALESCE(merchant,'')||' '||COALESCE(description,'')) LIKE ${'%'+matchText.toLowerCase()+'%'} RETURNING id`;matched+=matchedRows.length;const oldRules=Array.isArray(summary?.merchant_rules)?summary.merchant_rules:[],newRule={match_text:matchText,merchant:merchant||null,category,transaction_type:transactionType,created_at:new Date().toISOString()};summary={...summary,merchant_rules:[newRule,...oldRules.filter(rule=>String(rule?.match_text??'').toLowerCase()!==matchText.toLowerCase())].slice(0,200)};}
      const oldTripMap=summary?.trip_transaction_map&&typeof summary.trip_transaction_map==='object'?summary.trip_transaction_map:{},nextTripMap={...oldTripMap};if(tripId)nextTripMap[id]={trip_id:tripId,bucket:tripBucket,updated_at:new Date().toISOString()};else delete nextTripMap[id];summary={...summary,trip_transaction_map:nextTripMap};
      const oldTrueMap=summary?.true_expense_transaction_map&&typeof summary.true_expense_transaction_map==='object'?summary.true_expense_transaction_map:{},nextTrueMap={...oldTrueMap};const budgetSystem={...(summary?.budget_system??{})},funding={...(budgetSystem.funding??{}),true_expense_reserves:{...(budgetSystem.funding?.true_expense_reserves??{})}};const oldLink=nextTrueMap[id];
      if(oldLink?.fund_id){const oldFundId=String(oldLink.fund_id),restore=money(oldLink.reserve_consumed_nok),oldReserved=money(funding.true_expense_reserves?.[oldFundId]?.reserved_nok);if(restore>0)funding.true_expense_reserves[oldFundId]={...(funding.true_expense_reserves[oldFundId]??{}),reserved_nok:money(oldReserved+restore),updated_at:new Date().toISOString(),source:'restored_from_unlinked_transaction'};delete nextTrueMap[id];}
      let reserveConsumed=0;if(trueExpenseId){const expenseAmount=money(current[0].amount),available=money(funding.true_expense_reserves?.[trueExpenseId]?.reserved_nok);reserveConsumed=Math.min(expenseAmount,available);const left=money(available-reserveConsumed);if(left>0)funding.true_expense_reserves[trueExpenseId]={...(funding.true_expense_reserves[trueExpenseId]??{}),reserved_nok:left,updated_at:new Date().toISOString()};else delete funding.true_expense_reserves[trueExpenseId];nextTrueMap[id]={fund_id:trueExpenseId,expense_amount_nok:expenseAmount,reserve_consumed_nok:reserveConsumed,updated_at:new Date().toISOString()};}
      summary={...summary,true_expense_transaction_map:nextTrueMap,budget_system:{...budgetSystem,version:Math.max(4,Number(budgetSystem.version??1)),funding,updated_at:new Date().toISOString()}};
      await sql`UPDATE documents SET extracted_summary=${JSON.stringify(summary)}::jsonb WHERE id=${config.id}`;
      return res.status(200).json({ok:true,transaction:{...updated[0],trip_id:tripId,trip_bucket:tripBucket,true_expense_id:trueExpenseId,true_expense_reserve_consumed_nok:reserveConsumed,japan_wallet_transfer:walletLink},rule_saved:rememberRule,matched});
    }
    return res.status(405).json({error:'Method not allowed'});
  }catch(error){console.error(error);return res.status(500).json({error:'Kunne ikke behandle transaksjonen'});}
}
